# backend/app/services/intake/schemas.py
"""
Pydantic v2 Schemas for Clinical Intake Engine.

Purpose:
    Defines strict typed data models for patient demographics, clinical symptoms,
    LLM structured slot extraction, session memory state, and FastAPI HTTP request/response payloads.
"""

from typing import Optional, List, Dict, Any
from pydantic import BaseModel, Field


class PatientDemographics(BaseModel):
    """
    Data container for basic patient demographic slot information.
    
    Attributes:
        name (str, optional): Patient's full or preferred name.
        age (str, optional): Patient's age or birth date.
        gender (str, optional): Patient's identified gender.
        height (str, optional): Patient's height measurement.
        weight (str, optional): Patient's weight measurement.
        contact (str, optional): Patient's contact phone number or email.
    """
    name: Optional[str] = None
    age: Optional[str] = None
    gender: Optional[str] = None
    height: Optional[str] = None
    weight: Optional[str] = None
    contact: Optional[str] = None


class ClinicalSlots(BaseModel):
    """
    Data container for clinical symptom slot information collected during intake.
    
    Attributes:
        chief_complaint (str, optional): Primary reason for seeking medical care.
        onset_duration (str, optional): Timeline/duration of symptom onset.
        severity (str, optional): Pain/discomfort severity rating or description.
        pattern_triggers (str, optional): Constant vs intermittent pattern or worsening factors.
        current_medications (str, optional): Active medications or relevant medical history.
        patient_goals (str, optional): Specific questions or discussion points for the physician.
    """
    chief_complaint: Optional[str] = None
    onset_duration: Optional[str] = None
    quality: Optional[str] = None
    region_radiation: Optional[str] = None
    severity: Optional[str] = None
    pattern_triggers: Optional[str] = None
    current_medications: Optional[str] = None
    allergies: Optional[str] = None
    patient_goals: Optional[str] = None


class ExtractionResult(BaseModel):
    """
    Structured extraction output returned by the OpenAI Pydantic parser per conversation turn.
    
    Attributes:
        demographics (PatientDemographics, optional): Newly extracted demographic fields.
        clinical_slots (ClinicalSlots, optional): Newly extracted clinical symptom fields.
        next_question (str, optional): Single follow-up question generated by the LLM.
        is_emergency (bool): Red-flag indicator for severe or acute symptoms requiring urgent care.
        summary_brief (str, optional): Final Doctor Brief generated upon intake completion.
        quick_options (List[str]): Contextual suggestion chips for single-tap user responses.
    """
    demographics: Optional[PatientDemographics] = None
    clinical_slots: Optional[ClinicalSlots] = None
    next_question: Optional[str] = None
    is_emergency: bool = False
    red_flag_reason: Optional[str] = None
    summary_brief: Optional[str] = None
    quick_options: List[str] = Field(default_factory=list)
    # Explicit completion signal from the model itself. Don't rely solely on
    # patient_goals being non-empty — a patient declining ("nothing", "no
    # questions") is a valid, complete answer but may not populate that slot
    # with text. This flag lets the model say "intake is done" regardless of
    # exactly how the goals slot got filled.
    intake_complete: bool = False
    # Which of the 5 UI-facing stages the NEXT question (the one just generated)
    # belongs to. Must match Header.jsx's STAGES exactly:
    #   1 = Demographics & Reason   2 = Symptom Details
    #   3 = Interventions & Meds    4 = Doctor Questions
    #   5 = Doctor Brief (intake complete)
    # This is the primary driver of the progress bar — far more reliable than
    # reverse-engineering the stage from which slots happen to be filled, since
    # the model already knows which phase it's in when it writes the question.
    current_phase: Optional[int] = None


class IntakeSessionState(BaseModel):
    """
    Persistent session memory object tracking clinical intake progress across HTTP turns.
    
    Attributes:
        session_id (str): Unique identifier for the intake session.
        current_step (int): Active progression step (1 to 5).
        is_completed (bool): Flag indicating if all intake requirements have been satisfied.
        is_emergency (bool): Flag indicating if red-flag symptoms were flagged during intake.
        summary_brief (str, optional): Compiled Markdown summary brief for physician review.
        demographics (PatientDemographics): Accumulated demographic fields.
        clinical_slots (ClinicalSlots): Accumulated clinical symptom fields.
    """
    session_id: Optional[str] = "default_session"
    current_step: int = 1
    is_completed: bool = False
    is_emergency: bool = False
    summary_brief: Optional[str] = None
    demographics: PatientDemographics = Field(default_factory=PatientDemographics)
    clinical_slots: ClinicalSlots = Field(default_factory=ClinicalSlots)
    last_question_asked: Optional[str] = None
    # Rolling window of recent turns, e.g. [{"role": "assistant"/"user", "content": "..."}].
    # Capped in state.py to keep the prompt payload small.
    conversation_history: List[Dict[str, str]] = Field(default_factory=list)


class IntakeStepRequest(BaseModel):
    """
    Request payload schema for POST /api/v2/intake/step endpoint.
    
    Attributes:
        user_message (str): Raw text message entered or spoken by the patient.
        session_state (Dict[str, Any], optional): Current session memory dictionary from the frontend.
    """
    user_message: str
    session_state: Optional[Dict[str, Any]] = None


class IntakeStepResponse(BaseModel):
    """
    Response payload schema returned by POST /api/v2/intake/step endpoint.
    
    Attributes:
        updated_state (Dict[str, Any]): Updated session memory dictionary to persist in client state.
        next_question (str): Follow-up question to present to the patient.
        is_completed (bool): Indicates if the intake process is finalized.
        is_emergency (bool): Indicates if acute red-flag symptoms were detected.
        quick_options (List[str]): Suggested quick-reply options to render above the chat input.
    """
    updated_state: Dict[str, Any]
    next_question: str
    is_completed: bool = False
    is_emergency: bool = False
    quick_options: List[str] = Field(default_factory=list)